name       : haskell-cryptohash
version    : 0.11.9
release    : 2
source     :
    - http://hackage.haskell.org/package/cryptohash-0.11.9/cryptohash-0.11.9.tar.gz : c28f847fc1fcd65b6eea2e74a100300af940919f04bb21d391f6a773968f22fb
license    : BSD-3-Clause
component  : programming.haskell
summary    : A collection of crypto hashes, with a practical incremental and one-pass,
    pure APIs, with performance close to the fastest implementations available in
    other languages.
description: |
    A collection of crypto hashes, with a practical incremental and one-pass, pure APIs, with performance close to the fastest implementations available in other languages.
builddeps  :
    - haskell-byteable
    - haskell-cabal-install
    - haskell-cryptonite
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
